name    'hardening/hardening_stdlib'
version '0.1.0'
source 'https://github.com/TelekomLabs/puppet-hardening-stdlib'
author 'Dominik Richter'
license 'Apache License, Version 2.0'
summary 'Shared functions for hardening modules'
description 'Shared functions for hardening modules'
project_page 'https://github.com/TelekomLabs/puppet-hardening-stdlib'
